### PR TITLE
Update static-module

### PR DESCRIPTION
**Pull request by goto-bus-stop**
Fixes https://nodesecurity.io/advisories/548

### CODE REVIEW

**Comment by richardschneider** [comment]
@goto-bus-stop any progress on this PR?

**Comment by goto-bus-stop** [comment]
sorry, i forgot about it. i got a bit stuck on the test failure :/

**Comment by stevemao** [comment]
@goto-bus-stop could you fix the tests?

**Comment by goto-bus-stop** [comment]
Yep I'll put it on my agenda again. This one is a bit tough to fix, because static-eval returns undefined when it fails but also when the node actually evaluates to undefined. So when evaluating the arguments to path.join we can't just bail out whenever we see undefined.

Just writing that out made me think of a possible fix inside static-module tho!



On 18 January 2018 01:46:00 CET, Steve Mao <notifications@github.com> wrote:
>Assigned #83 to @goto-bus-stop.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/browserify/brfs/pull/83#event-1429465496

-- 
Sent from mobile. Please excuse my brevity.

**Comment by goto-bus-stop** [comment]
https://github.com/browserify/static-module/pull/39 should do it!

**Pull request merged**
